Ignore the cache and do the full look-ups as before
lxqt/libqtxdg pull request #255
Opened 2021-04-25 07:35 UTC by flychenjun

If the icon is not found in the cache, Do not need to clear the sub
directory, just ignore the cache and do a full lookup as before.

2021-04-25 13:00 UTC, tsujan commented
Please explain what problems your PR solves and a way of reproducing them without it.

2021-04-26 05:01 UTC, tsujan requested changes
The whole point of having a cache is to stop searching for the icon if it isn't in the cache. Don't get me wrong; I don't like this kind of cache but we should use it consistently if we use it at all.

2021-04-27 00:14 UTC, flychenjun commented
After installing a new application, the application icon is written below the path of the Hicolor, and the information is written to the cache. The icon may be read from Qicon: FROMTHEME, but when I install another new application, qiconcachegtkreader has read and loaded the cached file, and the newly installed application information has been written to the cache, but the Qiconcachegtkreader has not re-read the cached file, so the icon information for the new application can not be found in the cached file, at this point, the lookup path is cleared and can not be found from the full path。

2021-04-27 00:37 UTC, tsujan commented
That's https://github.com/lxqt/libqtxdg/issues. A real fix should not ignore the cache but read it when it's ready.

2021-04-27 01:00 UTC, flychenjun commented
Thanks for your help, I will check whether the icon information is written to the cache file correctly after installing the application

2021-04-27 01:12 UTC, tsujan commented
I think the cache is correct. I'm suspicious of our timing. Maybe `QFileSystemWatcher` should be used in another way...

2021-04-27 01:41 UTC, flychenjun commented
Yes, the cache is correct,  I received a signal that the cache file had been modified while I was tracking debugging. My requirement is that when a new application is installed on the system, my application receives a signal containing the name of the application, and then calls the QIcon:fromTheme interface to read the icon of the application, then it is possible that the update cache and installation completion signals are out of sequence and I need to check again.

2021-04-27 19:54 UTC, tsujan commented
Years ago, I also circumvented the cache, exactly like you did here and because of the same problem. My patch wasn't accepted for a good reason — the same reason I mentioned above.

Since then, I didn't find time to attack the problem again but I hope we could get rid of it once for all.

2021-05-19 00:30 UTC, flychenjun commented
dear tsujan:
    I think there's a problem with the logic of using a cache file here. The first time you install an application, when you use the QICON: fromTheme interface, you create a global object: Xdgiconloader, which read the cache file and can find the icon in the cache.
    but, after the second installation, when the QICON: fromTheme interface is used again, the cache is not re-read from the file again, and this code "cache->reValid(true)" is not executed in the "findIconHelper" function.
    so,I think the cache file needs to be loaded again after it has been modified.

2021-05-19 00:34 UTC, flychenjun commented
cache->isValid() || cache->reValid(true)
in this code ，these two conditions, when the previous condition is true, the latter condition is not executed.

2021-05-19 03:07 UTC, flychenjun commented
QIconCacheGtkReader::QIconCacheGtkReader(const QString &dirName)
    : m_cacheFileInfo{dirName + QLatin1String("/icon-theme.cache")}
    , m_data(nullptr)
    , m_isValid(false)
{
    m_file.setFileName(m_cacheFileInfo.absoluteFilePath());
    // Note: The cache file can be (IS) removed and newly created during the
    // cache update. But we hold open file descriptor for the "old" removed
    // file. So we need to watch the changes and reopen/remap the file.
    QObject::connect(gtkCachesWatcher(), &QFileSystemWatcher::fileChanged, &m_file, [this](const QString & path)
        {
             qDebug() << "Log info : QFileSystemWatcher::fileChanged, path :" << path;
            if (m_file.fileName() == path)
            {
                m_isValid = false;
                // invalidate icons to reload them ...
                QIconLoader::instance()->invalidateKey();
            }
        });
    reValid(false);
}


In this code, I added the log information, but no information was printed during debugging

2021-05-19 05:10 UTC, tsujan commented
> The first time you install an application,... which read the cache file and can find the icon in the cache

As mentioned in https://github.com/lxqt/libqtxdg/issues/226, the problem appears (randomly) with the *first* installation; subsequent uninstallations+ installations don't trigger it.

2021-06-03 05:54 UTC, tsujan commented
The problem may be related to and fixed by https://github.com/lxqt/libqtxdg/pull/261; I'm not sure though.

2021-06-11 02:00 UTC, closed without merging

2021-06-11 02:32 UTC, flychenjun commented
@tsujan 
I tested the code #261, I installed some wine-apps and the icons are refreshed in time.

2022-07-22 22:33 UTC, tsujan commented
@flychenjun
After more than a year, no one found a way better than yours. This is the same as https://github.com/lxqt/libqtxdg/pull/283, which I don't like it but, IMO, it's better than seeing `application-x-executable`.